<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hoa Binh_edit</name>
   <tag></tag>
   <elementGuidId>80b60546-d2d0-42e0-a6d0-f3bbef22ce56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='edit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;edit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5cf6de3c-0a19-48b9-834f-6e90767e8f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ed1f41c2-4bd9-4c72-b924-96a53014c825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>e8f2b4a6-e438-4862-a0e8-979ac0316159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sửa</value>
      <webElementGuid>c265e3bc-8785-46e9-a0b5-3dc9db250f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>edit</value>
      <webElementGuid>72a98b22-7115-4e4b-8489-101725177466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 text-center&quot;]/table[1]/tbody[1]/tr[2]/td[5]/form[1]/input[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>79c8dc29-0127-4dcb-acb0-adc946a5b408</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='edit']</value>
      <webElementGuid>9686f66d-9cd4-402d-bd8a-fe1fad051019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>dc5b7ad3-0aa0-4794-a017-c6c300c8d4a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'edit']</value>
      <webElementGuid>f6ab0f36-d14f-4642-9e0f-9fa1f8f65db3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
