<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_a ch_button</name>
   <tag></tag>
   <elementGuidId>7521c9c4-a846-4f19-b7de-acb14b9f7b23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Thêm khách hàng']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e56d0b1-6ac8-4e07-80f8-e5e9940727fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a0ef914c-2d65-4e38-b374-f7220e868d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>29e65e07-7c53-49e6-8454-1b23cc245c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Thêm khách hàng</value>
      <webElementGuid>bef62a8e-6986-47be-8acd-7ed610685103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client&quot;)/div[@class=&quot;input-group&quot;]/table[1]/tbody[1]/tr[7]/td[1]/input[@class=&quot;button&quot;]</value>
      <webElementGuid>ef3f22e5-c898-4c1b-94fe-3501097f2c9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Thêm khách hàng']</value>
      <webElementGuid>b2d2346b-0062-49ac-b4e6-af63692db0ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='client']/div/table/tbody/tr[7]/td/input</value>
      <webElementGuid>11577f82-4681-4f33-9248-1c2adef47f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/input</value>
      <webElementGuid>16fad2ab-6027-471b-bc60-65d716be3d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>6b7aded5-f390-4227-92c8-fc8f5da10f02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
